#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso myTwoPhaseMixtureThermo
wclean libso surfaceTensionModels
wclean libso myVoFphaseCompressibleTurbulenceModels

wclean


#------------------------------------------------------------------------------
